// stations
const HOBOKEN = 'HOBOKEN';
const NEWPORT = 'NEWPORT';

// routes
const PATH_HOB_TO_WTC = 'PATH_HOB_TO_WTC';
const PATH_HOB_TO_33RD = 'PATH_HOB_TO_33RD';
const PATH_JSQ_TO_33RD_VIA_HOB = 'PATH_JSQ_TO_33RD_VIA_HOB';
const PATH_JSQ_TO_33RD = 'PATH_JSQ_TO_33RD';
const PATH_WTC_TO_HOB = 'PATH_WTC_TO_HOB';
const PATH_33RD_TO_JSQ = 'PATH_33RD_TO_JSQ';

module.exports = {
    HOBOKEN: HOBOKEN,
    NEWPORT: NEWPORT,
    PATH_HOB_TO_WTC: PATH_HOB_TO_WTC,
    PATH_HOB_TO_33RD: PATH_HOB_TO_33RD,
    PATH_JSQ_TO_33RD_VIA_HOB: PATH_JSQ_TO_33RD_VIA_HOB,
    PATH_JSQ_TO_33RD: PATH_JSQ_TO_33RD,
    PATH_WTC_TO_HOB: PATH_WTC_TO_HOB,
    PATH_33RD_TO_JSQ: PATH_33RD_TO_JSQ,
};
