// stations
const HOBOKEN = 'HOBOKEN';

// routes
const PATH_HOB_TO_WTC = 'PATH_HOB_TO_WTC';
const PATH_HOB_TO_33RD = 'PATH_HOB_TO_33RD';
const PATH_JSQ_TO_33RD_VIA_HOB = 'PATH_JSQ_TO_33RD_VIA_HOB';

module.exports = {
    HOBOKEN: HOBOKEN,
    PATH_HOB_TO_WTC: PATH_HOB_TO_WTC,
    PATH_HOB_TO_33RD: PATH_HOB_TO_33RD,
    PATH_JSQ_TO_33RD_VIA_HOB: PATH_JSQ_TO_33RD_VIA_HOB,
};
