rows:
  - type: path
    title: PATH to 33rd
    origin: hoboken
    destination: thirtyThirdStreet
    walkMinutes: 10
  - type: nyWaterway
    title: Ferry to Brookfield
    origin: hobokenSouth
    destination: brookfield
    walkMinutes: 10
  - type: citiBike
    title: CitiBike Hudson & 4th
    stationId: 40add0a6-4250-46aa-8e75-939faa87f472
