rows:
  - type: path
    title: PATH to 33rd
    origin: hoboken
    destination: thirtyThirdStreet
    walkMinutes: 10
  - type: nyWaterway
    title: Ferry to Brookfield
    origin: hobokenSouth
    destination: brookfield
    walkMinutes: 10
  - type: citiBike
    title: CitiBike River & 4th
    stationId: "1839334257267825432"
  - type: clock
  - type: mta
    title: R southbound
    routeId: R
    stopId: R17S
    walkMinutes: 10
  - type: mta
    title: F northbound
    routeId: F
    stopId: D17N
    walkMinutes: 10
